# Generated by Django 5.0.2 on 2024-04-14 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageStock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='selectSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeSetor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gerenciar Setor',
                'verbose_name_plural': 'Gerenciar Setores',
            },
        ),
        migrations.CreateModel(
            name='cNota',
            fields=[
                ('titulo', models.CharField(max_length=255)),
                ('tag', models.CharField(default=0, max_length=12)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('fechada', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.selectsetor')),
            ],
            options={
                'verbose_name': 'Gerenciar Nota',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('total_horas', models.CharField(default=0, max_length=12)),
                ('itens_requisitados', models.TextField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_hexadecimal', models.CharField(editable=False, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('programado', 'Programado'), ('encerrado', 'Encerrado'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('encerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encerradas', to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalizadas', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.cnota')),
                ('orderm_criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageStock.produto')),
            ],
            options={
                'verbose_name': 'Gerenciar Ordem',
            },
        ),
    ]
